version: '3.8'

services:
  web:
    build: .
    container_name: my_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'my_database'
      MYSQL_USER: 'my_user'
      MYSQL_PASSWORD: 'my_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
